### PR TITLE
1.0 release as in #9

### PR DESCRIPTION
**Pull request by cole-brokamp**
work in progress; have not yet tested, but wanted to get it up for others to see

### CODE REVIEW

**Comment by cole-brokamp** [comment]
@erikarasnick we need to modify the entrypoint script to read in the correct columns. I was getting an error on the parser not matching the column names on `make test`

**Comment by erikarasnick** [comment]
One problem was that the make test command was using `simulated_jfs_data.csv` instead of `simulated_jfs_data_geocoded.csv`.  I can removed the un-geocoded version from this repo if that's helpful. 

However, I've had lots of other issues, mostly with packages and package versions. I did update to R 4.0.3 last week (I had to get admin access to install adobe reader, so I decided to update a few other things while I had it). I'm not sure if this is the issue or not... 

One random thing I'm running into now is that anytime `group_by()` is called, if I try to perform an action that doesn't require grouping or if I don't `ungroup()`, I get this error `attempt to bind a variable to R_UnboundValue`. I just solved this by ungrouping when needed.

Also when I run  `library()` from an .Rmd script Rstudio crashes?? 

Now I am getting errors installing packages in the container. For example, when I run `make build` during the `renv::restore()` call, I get this error: 
```
Error: failed to retrieve package 'dbplyr'
In addition: Warning message:
curl: (22) The requested URL returned error: 404
```
But if i shell into the container and run
```
remotes::install_version('dbplyr', version = '1.4.2', repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/focal/latest'))
```
it seems to install fine. I also tried re-running `make build`, thinking it might be an internet issue, but it stops in the same place or sometimes it stops when installing broom? 

This is long, but wanted to document today's journey. I will push up changes I have made so far.

**Comment by cole-brokamp** [comment]
I experienced the same issues with getting a 404 from RSPM.  Sometimes they work, sometimes they don't. I switched back to https://cran.rstudio.com for CRAN and seemed to not have any problems.  Maybe RSPM is experiencing down time?

**Comment by cole-brokamp** [comment]
I've gotten everything working.  @erikarasnick can you review and make sure it works for you?  You'll have to build from the Dockerfile here.  I haven't released anything yet.  Let me know and I'll merge in, add the release commit, and then push to DockerHub.

**Comment by cole-brokamp** [comment]
I also just cherry-picked in Andrew's fix for the chart axis colors and font sizes

**Comment by erikarasnick** [comment]
Yep, it's working for me!

**Pull request merged**
